/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eddy_androidstudy_daemon_DaemonWatcher */

#ifndef _Included_com_eddy_androidstudy_daemon_DaemonWatcher
#define _Included_com_eddy_androidstudy_daemon_DaemonWatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eddy_androidstudy_daemon_DaemonWatcher
 * Method:    openDaemonWatcher
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_eddy_androidstudy_daemon_DaemonWatcher_openDaemonWatcher
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
